@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Dec 09 10:58:06 +0700 2022
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim twoComConverter_Tester_behav -key {Behavioral:twoComConverter_sim:Functional:twoComConverter_Tester} -tclbatch twoComConverter_Tester.tcl -view D:/Education/year3/term1/HW_SYS_LAB/TermProject/VivadoProject/twoComConverter_Tester_behav.wcfg -log simulate.log"
call xsim  twoComConverter_Tester_behav -key {Behavioral:twoComConverter_sim:Functional:twoComConverter_Tester} -tclbatch twoComConverter_Tester.tcl -view D:/Education/year3/term1/HW_SYS_LAB/TermProject/VivadoProject/twoComConverter_Tester_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
